[project]
name = "example_project"
version = "0.1.0"
description = "An example Python project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest==8.3.5",
    "ruff==0.9.9",
]


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptooks.build_meta"


